const map = {
    class: 'zebes',
    shadowColor: 'rgb(188, 188, 188)',
    pixelWidth: 1920,
    pixelHeight: 1800,
    rows: 30,
    cols: 30,
    sectionRows: 15,
    sectionCols: 12,
    sectionStartCell: 421,
    rooms: [
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },

        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },

        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },

        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },

        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },

        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false }
    ]};

export default map;