const map = {
    class: 'overworld',
    shadowColor: 'rgb(97, 97, 35)',
    pixelWidth: 2048,
    pixelHeight: 704,
    rows: 8,
    cols: 16,
    sectionRows: 8,
    sectionCols: 16,
    sectionStartCell: 0,
    isHflipped: false,
    isVflipped: false,
    rooms: [
    { active: false },
    { active: true },
    { active: false },
    { active: true },
    { active: true },
    { active: true },
    { active: false },
    { active: true },
    { active: false },
    { active: false },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },

    { active: true },
    { active: false },
    { active: true },
    { active: true },
    { active: true },
    { active: false },
    { active: true },
    { active: false },
    { active: false },
    { active: false },
    { active: true },
    { active: false },
    { active: true },
    { active: true },
    { active: true },
    { active: true },

    { active: false },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: false },
    { active: false },
    { active: false },
    { active: true },
    { active: true },
    { active: false },
    { active: true },

    { active: false },
    { active: false },
    { active: false },
    { active: true },
    { active: true },
    { active: false },
    { active: false },
    { active: true },
    { active: false },
    { active: false },
    { active: false },
    { active: false },
    { active: true },
    { active: true },
    { active: false },
    { active: false },

    { active: false },
    { active: false },
    { active: true },
    { active: false },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: false },
    { active: true },
    { active: true },
    { active: false },

    { active: false },
    { active: true },
    { active: false },
    { active: false },
    { active: false },
    { active: false },
    { active: true },
    { active: false },
    { active: false },
    { active: false },
    { active: false },
    { active: true },
    { active: false },
    { active: false },
    { active: true },
    { active: false },

    { active: false },
    { active: false },
    { active: true },
    { active: true },
    { active: true },
    { active: false },
    { active: true },
    { active: true },
    { active: true },
    { active: false },
    { active: true },
    { active: true },
    { active: false },
    { active: true },
    { active: false },
    { active: true },

    { active: true },
    { active: true },
    { active: false },
    { active: false },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: true },
    { active: false },
    { active: true },
    { active: true },
    { active: true },
    { active: false },
    { active: false }
]};

export default { data: map };