<script>
	import { onMount } from 'svelte';
	import { each } from 'svelte/internal';
    import tilesheet from '../tilesheet.js';
    import areamap from '../areamap.js'

    const mapTilesheet = new tilesheet(
        '/images/dungeons-halfscale.png',
        2048, 1408, 16, 16, 3, 8, 13
    );

    const mapState = [
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false }
    ];

  const roomStates = ['cleared', 'warp', 'equip', 'quest'];
  const levelQ1Map = new areamap('Level 2', mapTilesheet, roomStates, mapState);

    //  Dynamic style vars
    let styles = {
      'map-cols': 16,
      'map-rows': 16,
      'level-cols': 3,
      'level-rows': 8,
      'shadow-color': 'rgb(32, 56, 236)',
      'bg-uri': `url("${mapTilesheet.bguri()}")`,
      'aspect': `${mapTilesheet.pxWidth() / mapTilesheet.pxHeight()}`
    };

    $: cssVarStyles = Object.entries(styles)
		.map(([key, value]) => `--${key}:${value}`)
		.join(';');

	export let name;

	onMount(() => {
    });
</script>

<div style="{cssVarStyles}">
  <h2>{name}</h2>
  <p>xxx rooms.  16x16 tiles.  2048 x 1408 px total.</p>

  <!-- <img src="/images/hyrule-q1-halfscale.png" alt="" /> -->
  <div class="grid-container">
    {#each mapState as cell,index (mapTilesheet.sectionStartCell() + index)}
      <p class="hyrule-q1" class:active={cell.active} class:oob={cell.outofbounds}></p>
    {/each}
  </div>
</div>

<style>
  .oob {
    opacity: 0;
  }

  /* .hyrule-q1:not(.oob) {
		filter: saturate(120%)
	} */

	/* .hyrule-q1:not(.active) {
		filter: opacity(70%) saturate(70%)
	} */

	.hyrule-q1:not(.oob):hover {
		z-index: 10;
		cursor: pointer;

		filter: drop-shadow(10px 10px 10px var(--shadow-color));
		-webkit-animation: scale-up-center 0.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
		animation: scale-up-center 0.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	}

  /* ----------------------------------------------
  * Generated by Animista on 2021-5-8 23:11:36
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation scale-up-center
  * ----------------------------------------
  */
  @-webkit-keyframes scale-up-center {
    0% {
      -webkit-transform: scale(1);
              transform: scale(1);
    }
    100% {
      -webkit-transform: scale(1.15);
              transform: scale(1.15);
    }
  }
  @keyframes scale-up-center {
    0% {
      -webkit-transform: scale(1);
              transform: scale(1);
    }
    100% {
      -webkit-transform: scale(1.15);
              transform: scale(1.15);
    }
  }

	.grid-container {
		display: grid;
    grid-template-columns: repeat(var(--level-cols), calc(100% / var(--level-cols)));
		grid-template-rows: repeat(var(--level-rows), calc(100% / var(--level-rows)));
		gap: 1px;
		aspect-ratio: var(--aspect);
	}

	.hyrule-q1 {
		display: flex;
		flex-direction: column;
		flex: 1;
    background: url(/images/dungeons-halfscale.png);
		background-size: calc(var(--map-cols) * 100%) calc(var(--map-rows) * 100%);
	}


  /*  Rows  */
	.hyrule-q1:nth-child(-n+3) {
		background-position-y: 0;
	}

  .hyrule-q1:nth-child(n+4):nth-child(-n+6) {
		background-position-y: calc(1 * 100% / (var(--map-cols) - 1));
	}

  .hyrule-q1:nth-child(n+7):nth-child(-n+9) {
		background-position-y: calc(2 * 100% / (var(--map-cols) - 1));
	}

  .hyrule-q1:nth-child(n+10):nth-child(-n+12) {
		background-position-y: calc(3 * 100% / (var(--map-cols) - 1));
	}

  .hyrule-q1:nth-child(n+13):nth-child(-n+15) {
		background-position-y: calc(4 * 100% / (var(--map-cols) - 1));
	}

  .hyrule-q1:nth-child(n+16):nth-child(-n+18) {
		background-position-y: calc(5 * 100% / (var(--map-cols) - 1));
	}

  .hyrule-q1:nth-child(n+19):nth-child(-n+21) {
		background-position-y: calc(6 * 100% / (var(--map-cols) - 1));
	}

  .hyrule-q1:nth-child(n+22):nth-child(-n+24) {
		background-position-y: calc(7 * 100% / (var(--map-cols) - 1));
	}


  /*  Columns  */
  .hyrule-q1:nth-child(3n-2) {
		background-position-x: calc(12 * 100% / (var(--map-rows) - 1));
	}

  .hyrule-q1:nth-child(3n-1) {
		background-position-x: calc(13 * 100% / (var(--map-rows) - 1));
	}

  .hyrule-q1:nth-child(3n) {
		background-position-x: calc(14 * 100% / (var(--map-rows) - 1));
	}
</style>