const map = {
    class: 'level9 dungeon',
    shadowColor: 'rgb(188, 188, 188)',
    pixelWidth: 2048,
    pixelHeight: 1408,
    rows: 16,
    cols: 16,
    sectionRows: 8,
    sectionCols: 8,
    sectionStartCell: 136,
    isHflipped: false,
    isVflipped: false,
    rooms: [
    { outofbounds: true },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },

    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },

    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },

    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },

    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },

    { outofbounds: true },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: true },

    { outofbounds: true },
    { outofbounds: false },
    { outofbounds: true },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: true },
    { outofbounds: false },
    { outofbounds: true }
]};

export default { data: map };