const map = {
    class: 'level7 dungeon',
    shadowColor: 'rgb(0, 168, 0)',
    pixelWidth: 2048,
    pixelHeight: 1408,
    rows: 16,
    cols: 16,
    sectionRows: 8,
    sectionCols: 6,
    sectionStartCell: 128,
    isHflipped: false,
    isVflipped: false,
    rooms: [
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false, premark: 'E' },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: true },

    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false, premark: 'U' },
    { outofbounds: false, premark: 'Q' },
    { outofbounds: true },
    { outofbounds: true },

    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: true },
    { outofbounds: true },
    { outofbounds: true },

    { outofbounds: false, premark: 'U' },
    { outofbounds: false },
    { outofbounds: true },
    { outofbounds: true },
    { outofbounds: true },
    { outofbounds: true },
    
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: true },
    { outofbounds: true },

    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },

    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: false },
    { outofbounds: true },
    { outofbounds: true },
    { outofbounds: true }
]};

export default { data: map };