const map = {
    class: 'norfair zebes',
    shadowColor: 'rgb(188, 188, 188)',
    pixelWidth: 1920,
    pixelHeight: 1800,
    rows: 30,
    cols: 30,
    sectionRows: 13,
    sectionCols: 18,
    sectionStartCell: 282,
    isHflipped: false,
    isVflipped: false,
    rooms: [
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false }
    ],
    gridRegions: [
        { name: 'north-hall-top',
          rowStart: 1, rowEnd: 1, colStart: 16, colEnd: 18,
          bgSize: 'calc(var(--map-cols) * 100% / 2) calc(var(--map-rows) * 100%)',
          bgPosX: '96.4%',
          bgPosY: 'calc(9 * 100% / 29)'
        },
        { name: 'north-hall-mid',
          rowStart: 2, rowEnd: 2, colStart: 16, colEnd: 18,
          bgSize: 'calc(var(--map-cols) * 100% / 2) calc(var(--map-rows) * 100%)',
          bgPosX: '96.4%',
          bgPosY: 'calc(10 * 100% / 29)'
        },
        { name: 'north-hall-bottom',
          rowStart: 3, rowEnd: 3, colStart: 13, colEnd: 18,
          bgSize: 'calc(var(--map-cols) * 100% / 5) calc(var(--map-rows) * 100%)',
          bgPosX: '96.0%',
          bgPosY: 'calc(11 * 100% / 29)'
        },
        { name: 'left-entrance-hall',
          rowStart: 5, rowEnd: 5, colStart: 2, colEnd: 10,
          bgSize: 'calc(var(--map-cols) * 100% / 8) calc(var(--map-rows) * 100%)',
          bgPosX: '59.1%',
          bgPosY: 'calc(13 * 100% / 29)'
        },
        { name: 'right-entrance-hall',
          rowStart: 5, rowEnd: 5, colStart: 11, colEnd: 18,
          bgSize: 'calc(var(--map-cols) * 100% / 7) calc(var(--map-rows) * 100%)',
          bgPosX: '95.7%',
          bgPosY: 'calc(13 * 100% / 29)'
        },
        { name: 'left-entrance-hall-extended',
          rowStart: 6, rowEnd: 6, colStart: 2, colEnd: 6,
          bgSize: 'calc(var(--map-cols) * 100% / 4) calc(var(--map-rows) * 100%)',
          bgPosX: '50.0%',
          bgPosY: 'calc(14 * 100% / 29)'
        },
        { name: 'screw-attack',
          rowStart: 7, rowEnd: 7, colStart: 3, colEnd: 6,
          bgSize: 'calc(var(--map-cols) * 100% / 3) calc(var(--map-rows) * 100%)',
          bgPosX: '51.9%',
          bgPosY: 'calc(15 * 100% / 29)'
        },
        { name: 'high-jump',
          rowStart: 8, rowEnd: 8, colStart: 15, colEnd: 18,
          bgSize: 'calc(var(--map-cols) * 100% / 3) calc(var(--map-rows) * 100%)',
          bgPosX: '96.3%',
          bgPosY: 'calc(16 * 100% / 29)'
        },
        { name: 'last-area-you-ever-check',
          rowStart: 9, rowEnd: 11, colStart: 13, colEnd: 18,
          bgSize: 'calc(var(--map-cols) * 100% / 5) calc(var(--map-rows) * 100% / 2)',
          bgPosX: '96.0%',
          bgPosY: '60.7%'
        },
        { name: 'second-last-area-to-check',
          rowStart: 11, rowEnd: 11, colStart: 10, colEnd: 17,
          bgSize: 'calc(var(--map-cols) * 100% / 7) calc(var(--map-rows) * 100%)',
          bgPosX: '91.3%',
          bgPosY: 'calc(19 * 100% / 29)'
        },
        { name: 'wave-beam',
          rowStart: 12, rowEnd: 12, colStart: 6, colEnd: 9,
          bgSize: 'calc(var(--map-cols) * 100% / 3) calc(var(--map-rows) * 100%)',
          bgPosX: '66.6%',
          bgPosY: 'calc(20 * 100% / 29)'
        },
        { name: 'pre-wave-beam-check',
          rowStart: 13, rowEnd: 13, colStart: 6, colEnd: 8,
          bgSize: 'calc(var(--map-cols) * 100% / 2) calc(var(--map-rows) * 100%)',
          bgPosX: '60.7%',
          bgPosY: 'calc(21 * 100% / 29)'
        }
    ]
};

export default { data: map };