const map = {
    class: 'ridleys zebes',
    shadowColor: 'rgb(147, 8, 65)',
    pixelWidth: 1920,
    pixelHeight: 1800,
    rows: 30,
    cols: 30,
    sectionRows: 8,
    sectionCols: 17,
    sectionStartCell: 673,
    isHflipped: false,
    isVflipped: false,
    rooms: [
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false, active: false },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },

        { outofbounds: false, active: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false, active: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false, active: false },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false, active: false },

        { outofbounds: false, premark: 'M' },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false, premark: 'U' },
        { outofbounds: false, premark: 'M' },
        { outofbounds: false, premark: 'M' },
        { outofbounds: false, premark: 'M' },
        { outofbounds: false, premark: 'M' },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false, active: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },

        { outofbounds: false, premark: 'M' },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: true },
        { outofbounds: false },

        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },

        { outofbounds: false, premark: 'M' },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false, premark: 'U' },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false },
        { outofbounds: false }
    ],
    gridRegions: [
        { name: 'varia-hall',
          rowStart: 2, rowEnd: 2, colStart: 5, colEnd: 10,
          bgSize: 'calc(var(--map-cols) * 100% / 5) calc(var(--map-rows) * 100%)',
          bgPosX: '68.0%',
          bgPosY: 'calc(23 * 100% / 29)',
          premark: 'U'
        },
        { name: 'top-left-connector',
          rowStart: 3, rowEnd: 3, colStart: 2, colEnd: 4,
          bgSize: 'calc(var(--map-cols) * 100% / 2) calc(var(--map-rows) * 100%)',
          bgPosX: '50.0%',
          bgPosY: 'calc(24 * 100% / 29)'
        },
        { name: 'mid-left-connector',
          rowStart: 5, rowEnd: 5, colStart: 2, colEnd: 4,
          bgSize: 'calc(var(--map-cols) * 100% / 2) calc(var(--map-rows) * 100%)',
          bgPosX: '50.0%',
          bgPosY: 'calc(26 * 100% / 29)'
        },
        { name: 'ridleys-booty',
          rowStart: 7, rowEnd: 7, colStart: 2, colEnd: 4,
          bgSize: 'calc(var(--map-cols) * 100% / 2) calc(var(--map-rows) * 100%)',
          bgPosX: '50.0%',
          bgPosY: 'calc(28 * 100% / 29)',
          premark: 'Q'
        },
        { name: 'ridleys-hall',
          rowStart: 7, rowEnd: 7, colStart: 5, colEnd: 9,
          bgSize: 'calc(var(--map-cols) * 100% / 4) calc(var(--map-rows) * 100%)',
          bgPosX: '65.4%',
          bgPosY: 'calc(28 * 100% / 29)'
        },
        { name: 'mid-left-hall',
          rowStart: 5, rowEnd: 5, colStart: 5, colEnd: 9,
          bgSize: 'calc(var(--map-cols) * 100% / 4) calc(var(--map-rows) * 100%)',
          bgPosX: '65.4%',
          bgPosY: 'calc(26 * 100% / 29)'
        },
        { name: 'the-yump',
          rowStart: 5, rowEnd: 5, colStart: 10, colEnd: 12,
          bgSize: 'calc(var(--map-cols) * 100% / 2) calc(var(--map-rows) * 100%)',
          bgPosX: '78.5%',
          bgPosY: 'calc(26 * 100% / 29)',
          premark: 'U'
        },
        { name: 'knowledge-hall',
          rowStart: 5, rowEnd: 5, colStart: 12, colEnd: 17,
          bgSize: 'calc(var(--map-cols) * 100% / 5) calc(var(--map-rows) * 100%)',
          bgPosX: '96.0%',
          bgPosY: 'calc(26 * 100% / 29)',
          premark: 'U'
        },
        { name: 'intro-hall',
          rowStart: 3, rowEnd: 3, colStart: 13, colEnd: 17,
          bgSize: 'calc(var(--map-cols) * 100% / 4) calc(var(--map-rows) * 100%)',
          bgPosX: '96.1%',
          bgPosY: 'calc(24 * 100% / 29)'
        }
    ]
};

export default { data: map };